### ISSUE TITLE
Request 받아서 추후 동작 처리

### ISSUE THREAD

**Issue by davkim1030** [davkim1030/webserv#13]
- [x] 요청에 따라 알맞은 status code 반환
- [ ] 파일의 종류에 따라 cgi 호출하여 처리된 데이터 반환(ex- .php, .py 등)
- [x] 클라이언트에 돌려주는 값은 항상 `HttpResponse` 메시지

**Comment by seohee-choi** [comment]
- [x] **GET 요청시 해당 파일/디렉토리 찾아서 리스폰스 반환**
- [x] 입력받은 URI가 유효한지 검사하기
- [x] HTML 파일 만들기
- [x] 입력받은 URI로 접속이 가능한지 테스트하기
- [x] 요청 들어온 파일을 처리해서 Body에 담기
- [x] 엔티티 헤더 처리하기
- [x] 컨텐츠 헤더 처리하기

**Comment by seohee-choi** [comment]
헤더는 브라우저에서 알아서 잘 만들어주고 우리는 invalid한 URL을 핸들링할 의무가 없기 때문에 입력받은 URI가 유효한지 검사하는 부분은 무시하기로 결론

**Comment by skamo3** [comment]
uri를 받아오는 부분에서의 ISSUE
<img width="627" alt="Screen Shot 2021-06-09 at 4 10 51 PM" src="https://user-images.githubusercontent.com/54701846/121309552-46073e80-c93d-11eb-9831-1ebd4da6c9d7.png">
처음 uri를 받아서 location에서 검색할 때 uri 그대로 검색을 하게 되는데
이 때 `localhost:80/dir/test.cgi`
이런식의 형태로 들어오면 아무것도 찾지 못해서 getUri를 해서 uri를 받아온 후 다시한번 directory 단위로 파싱하는 단계를 거쳐야 할것 같습니다

**Comment by seohee-choi** [comment]
> uri를 받아오는 부분에서의 ISSUE
> <img alt="Screen Shot 2021-06-09 at 4 10 51 PM" width="627" src="https://user-images.githubusercontent.com/54701846/121309552-46073e80-c93d-11eb-9831-1ebd4da6c9d7.png">
> 처음 uri를 받아서 location에서 검색할 때 uri 그대로 검색을 하게 되는데
> 이 때 `localhost:80/dir/test.cgi`
> 이런식의 형태로 들어오면 아무것도 찾지 못해서 getUri를 해서 uri를 받아온 후 다시한번 directory 단위로 파싱하는 단계를 거쳐야 할것 같습니다

Uri: localhost:80
Directory: dir/test.cgi
이렇게 파싱하면 될까요?

**Comment by skamo3** [comment]
아뇨아뇨 uri부분에 /dir/test.cgi 가 들어올테니
/dir/ 이 저희가 참조할 폴더라고 생각해요!
그 안에 있는 test.cgi를 가져오는거니까요
근데 location은 location에 있는 path로 봐야하지 않나 싶어요

**Comment by seohee-choi** [comment]
아 그러면 Location검색 변수가 /dir/이 되게 uri를 파싱 하고
기존 input은 따로 또 쓸 수 있게 rawUri 변수로 만들어두겠습니다

**Comment by skamo3** [comment]
넴!!

**Comment by seohee-choi** [comment]
Request에 TRANSFER_ENCODING헤더가 chucked 밸류로 들어오는 경우 핸들링
