### ISSUE TITLE
cgi 처리

### ISSUE THREAD

**Issue by davkim1030** [davkim1030/webserv#14]

**Comment by skamo3** [comment]
CGI 처리하기
- GET
  - 쿼리를 파싱해서 넘겨주기
- POST 
  - 바디가 곧 쿼리
- Meta-Variables 구현하기
  - subject 참고
- chunked request의 경우 unchunk해서 body를 만든 후 EOF로 끝내줘야 함

**Comment by skamo3** [comment]
# CGI 처리 시 envp에 담아서 보내줘야 하는 변수들 (meta-variables)
- AUTH_TYPE
    - 서버가 유저 인증(user authentication)을 지원하고 스크립트가 보호되는 경우 사용자 검증에 사용되는 프로토콜 인증 방식
    - ex) SSL, BASIC 등등
- CONTENT_LENGTH
    - client로 부터 받을 content의 길이
- CONTENT_TYPE
    - HTTP, POST, PUT 같은 정보가 첨부된 쿼리의 경우 데이터 내용 유형
    - 기본적으로 HTTP 정보 파싱 시에 들어오는 CONTENT_TYPE을 사용하면 됨
- GATEWAY_INTERFACE
    - 서버가 따르는 CGI 규격의 버전
    - ex) CGI/revision or  CGI/1.1
- PATH_INFO
    - 클라이언트에서 제공하는 추가 경로 정보
    - 스크립트는 이 가상 경로에 access할 수 있으며 경로 끝에 추가 정보가 표시 됨
    - 추가 정보는 PATH_INFO로 전달되고 이 정보는 CGI 스크립트로 전달 전에 URL로 전달된 경우 서버에서 디코딩 해야함
    - 기본 경로 외에 cgi 를 불러올 가상 경로를 말하는 듯함
- PATH_TRANSLATED
    - 스크립트의 가상 경로를 스크립트 호출에 사용되는 실제 경로에 맵핑
    - 요청 URI의 PATH_INFO 구성 요소를 가져와 {가상 경로 : 실제 경로} 변환을 해줌
- QUERY_STRING
    - URL에 포함되는 정보 목록
    - ? 뒤에 붙어있고 key=value 형태로 들어옴
    - ex) localhost:80/test/?key1=val1/key2=val2
- REMOTE_ADDR
    - 요청을 수행하는 사용자의 원격 IP 주소
- REMOTE_IDENT
    - RFC 931을 지원하는 경우 서버에서 검색된 원격 사용자 이름으로 설정 됨
    - 이 변수는 로깅을 위해 사용
- REMOTE_USER
    - 서버가 authentication을 지원하고 script가 보호되는 경우 authentication 프로세스로 전달되는 username
- REQUEST_METHOD
    - 리퀘스트 메소드
    - HTTP GET POST HEAD 등등
    - allow_method들이 해당됨
- REQUEST_URI
    - 리퀘스트로 들어오는 uri
    - uri 넣어주면 될듯
- SCRIPT_NAME
    - 스크립트의 가상 경로 이름
- SERVER_NAME
    - 서버의 호스트의 이름
- SERVER_PORT
    - 리퀘스트가 들어온 서버 호스트 포트
- SERVER_PROTOCOL
    - 서버에서 사용된 프로토콜 이름
    - 포맷 : protocol/revision
    - ex) HTTP/1.1
- SERVER_SOFTWARE
    - 클라이언트의 요청에 답하고 있는 서버 소프트웨어의 이름 및 버전
    - 내 서버니 원하는대로 지정하면 됨
