### ISSUE TITLE
Location 검색 위한 Request URI 파싱 추가

### ISSUE THREAD

**Issue by seohee-choi** [davkim1030/webserv#19]
![](https://user-images.githubusercontent.com/54701846/121309552-46073e80-c93d-11eb-9831-1ebd4da6c9d7.png)

이슈 : URI를 location에서 검색할 때 날것의 URI로 그대로 검색을 하게 되는데, 이 때 URI Request가 localhost:80/dir/test.cgi 이런식의 형태로 들어오면 아무것도 찾지 못하게 됨
getUri를 해서 uri를 받아온 후 다시한번 directory 단위로 파싱하는 단계를 거쳐야 할것 같다.

**Comment by skamo3** [comment]
파싱 방식 업데이트 이슈

cgi가 들어올 경우 uri 경우의 수

```

1) /test/
2) /test/test.bla
3) /test/test.bla?query_string
4) /test/test.bla/path/
5) /test/test.bla/path/?query_string

```

현재 parseDirectory 에서 3, 4, 5 번의 경우 처리가 안될 것으로 예상중입니다 확인 부탁드려요

**Comment by seohee-choi** [comment]
3. 쿼리스트링 떼주기(stat 불가) 
4. 가상경로 떼주기?? 삭제해주기?? 처리해주기
5.

**Comment by skamo3** [comment]
저 가상경로와 쿼리스트링은 cgi에서 사용하기때문에 아예 날려버려서 가져오면 큰일납니다!
rawUri에선 그대로 들고 다니다가 getLocation 하는 부분에서만 처리를 해주는게 베스트일거같다고 생각해요

**Comment by seohee-choi** [comment]
getLocation에서는 쿼리스트링/가상경로를 떼주고 rawUri에서는 그대로 두는 방식으로 하겠습니다.
그런데 stat으로 파일 오픈 테스트할 때 rawUri으로 쿼리스트링이 붙은 것까지 한번에 판단하기때문에
rawUri, Location(파일명/쿼리스트링/가상경로 제거한 경로), Uri(쿼리스트링/가상경로 제거한 경로) 로 변수를 세개로 설정해야할것같습니다.

**Comment by skamo3** [comment]
뒷부분은 서희님이 편한 방법으로 하시면 될거같습니다 원본이 남아있다면 cgi에서는 큰 문제는 없어요!!

**Comment by skamo3** [comment]
/test/test.bla/path/ 일 때
parseDirectory 함수에서 / 를 4개인걸로 읽어서 파싱하는 방법을 사용하셨는데 
뒤의 path는 가상경로임을 나타내는 용어이기에 바꿔주어야 합니다
path = /test/dir1/dir2 같은 형태가 될 수도 있습니다
