### ISSUE TITLE
Tester 이슈 잡아내기

### ISSUE THREAD

**Issue by davkim1030** [davkim1030/webserv#24]
- Tester를 돌려보며 틀린 부분들 하나씩 수정
- 문제 수정 시작, 끝낼 때마다 comment로 수정했다고 올려주세욥

**Comment by davkim1030** [comment]
~~allowed_method에 HEAD가 없을 때 200말고 405 status_code를 리턴하게 해주세요~~

![image](https://user-images.githubusercontent.com/7599727/121800878-3a828300-cc6f-11eb-8f8a-8100a0ddba8d.png)
브랜치 [tester_resolve](https://github.com/davkim1030/webserv/tree/tester_resolve)에서 처리했습니다

**Comment by seohee-choi** [comment]
```
	location /directory/ {
		root ./test/
```
~~처럼 로케이션과 루트가 다른 경우 404에러 발생 -> 해당이유가아니라 .//test/test.html처럼 맨앞에 루트가 문제였음 (고치는중)~~

#29  에서 해결

**Comment by seohee-choi** [comment]
```
	location / {
...
	location /directory/ {
```

와 같은 config파일에서, /directory/경로로 접속할경우, '완전히 일치하는' 경로를 찾지않고 가장 먼저 찾아진 것을 반환하는 문제


*****
getLocation 함수에서, 가장먼저 요청 URI와 완전히 '일치하는' location이 있는지 1차 탐색->이후 location이 '포함된' URI이 존재하는지 찾는 방식으로 수정

**Comment by seohee-choi** [comment]
<img width="230" alt="image" src="https://user-images.githubusercontent.com/60740882/121802476-5853e600-cc77-11eb-99dc-5e6886843b15.png">
localhost:8080/test/ 로 접속시 main.css가 불리는 문제

**Comment by seohee-choi** [comment]
config파일에 없는 location 접속시 segmentation fault  발생

**Comment by seohee-choi** [comment]
~~GET 으로 디렉토리가 들어올때, 폴더에 index파일이 없고 autoindex가 꺼져있을 경우 404가 아닌 500에러 반환하는문제~~

폴더에 index 파일이 없고 autoindex가 꺼져있을경우 NOT_FOUND가 바로 반환되지않고 read로 넘어가는 문제였음. 처리.

**Comment by seohee-choi** [comment]
![image](https://user-images.githubusercontent.com/60740882/122214675-57c08700-cee5-11eb-81c2-717199d4962a.png)
chunked PUT 될경우 오류
해당경로가 config파일에 없어서 405가 반환되는 오류였음->
config파일에 해당경로 넣어주고나니, 파일생성은 되는데 내용물이 들어가지않음 ->
청크드 입력이 제대로 안됨 문제

**Comment by seohee-choi** [comment]
<img width="737" alt="image" src="https://user-images.githubusercontent.com/60740882/122330869-e2999400-cf6e-11eb-92e0-f9929aaa4e6e.png">
한 서버에서 테스터를 여러번 돌리면 위와같이 뜹니다

**Comment by seohee-choi** [comment]
~~테스터 돌릴 때마다
` Unsolicited response received on idle HTTP channel starting with "\r\n"; err=<nil>`
이라고 출력되는 문제~~

body 마지막줄에 \r\n이 들어가있어서 그랬습니다 해결

**Comment by seohee-choi** [comment]
Test Put http://localhost:8080/put_test/file_should_exist_after with a size of 10000000
FATAL ERROR ON LAST TEST: Put http://localhost:8080/put_test/file_should_exist_after: EOF

천만사이즈 put 터짐
