### ISSUE TITLE
nginx.config에서 다른 서버에서 동일한 포트가 들어 왔을 때 처리

### ISSUE THREAD

**Issue by davkim1030** [davkim1030/webserv#28]
```config
server {
  server_name NGINX;
  port 8083;
}

server {
  server_name TT;
  port 8083;
}
```

위와 같이 포트가 겹치는 다른 서버 정보를 가진 config 파일이 들어온 경우
1. `ServerConfig`의 파싱 부분에서 에러 처리
2. 여러 개 중 하나의 값만 `ServerConfig::Server`에 저장
중 하나의 행동을 해야 하는데 현재는 아래와 같이 모두 저장함
![image](https://user-images.githubusercontent.com/7599727/122055029-2e3f2700-ce23-11eb-8600-362d6a62bb34.png)

중복 값 처리 필요

**Comment by seohee-choi** [comment]
test-resolve 브랜치에서 listen 뒤에 들어오는 포트넘버가 중복되었을 경우 ~~두번째 값부터는 저장하지 않도록 처리하겠습니다.~~ 어쩐지 인벨리드 때려버리고싶어서 오류처리하겠습니다.

**Comment by seohee-choi** [comment]
server의 port는 ServerConfig 함수에서 생성된 Server객체::sliceOptions 함수에서 처리되다보니 각각의 서버 객체가 나뉜 뒤에 그 객체들이 내용을 또다시 파싱하는 방식이라서 파싱도중 객체간의 간섭이 어렵지 않을까 하는 생각이 들었습니다. 

파싱을 하는 도중 이전 server객체들이 가지고 있는 port와 일일이 대조하여 비교하려 했으나 어려울 것 같아서
파싱을 완료한 다음 상위함수(serverConfig함수)에서 파싱된 객체들을 대조해 비교하도록 하겠습니다.
