### ISSUE TITLE
리소스 파일을 직접 리퀘스트 날리지 않으면 Content-Type이 text/plain으로 오는 이슈

### ISSUE THREAD

**Issue by davkim1030** [davkim1030/webserv#32]
- http://localhost:8082/ 로 리퀘스트를 보내면 `Content-Type`이 `text/plain`으로 와서 브라우저에서 이상하게 보임
- http://localhost:8082/index.html로 보내면 `Content-Type`이 `text/html`으로 와서 잘 보임

**Comment by seohee-choi** [comment]
해당이슈 재현해보았으나 정상작동하였습니다. text/plain으로 날아온 경우의 환경에 대해 더 말씀해주실 수 있을까요?

**Comment by davkim1030** [comment]
현재 `origin/tmp_branch` 브랜치의 최신 커밋으로 동작시키면 해당 에러가 나옵니다.
<img width="1331" alt="스크린샷 2021-06-25 오후 5 19 49" src="https://user-images.githubusercontent.com/7599727/123394132-c2567e80-d5d9-11eb-9737-f73b89f92ba1.png">

**Comment by seohee-choi** [comment]
문제 발생 확인했습니다.

**Comment by seohee-choi** [comment]
문제발생원인
- index 파일을 확인하고 읽어오는 함수`ResourceHandler` 와 헤더를 추가하고 Response를 생성해서 보내는 곳 `ResponseHandler`이 분리되어있음
- content-type 헤더를 추가할 때 index파일의 경로를 제대로 읽지 못해 text/plain 설정

문제해결방법
1. `ResponseHandler`에서도 index파일의 경로를 가져오는 부분을 추가한다
2. 그게 아니라면, `ResourceHandler`의 경로를 `ResponseHandler`에서 받아볼 수 있게 한다.
