### ISSUE TITLE
cgi로 기본 헤더 이외를 헤더를 넣어서 보내면 생기는 에러

### ISSUE THREAD

**Issue by davkim1030** [davkim1030/webserv#34]
```
Test POST http://localhost:8082/directory/youpi.bla with a size of 100000 with special headers
FATAL ERROR ON LAST TEST: bad cgi returned body content
```

-> cgi를 실행 시킬  때, 헤더 값들을 envp로 넘겨주지 않아서 생기는 에러

- Request
```
POST /directory/youpi.bla HTTP/1.1
Host: localhost:8080
X-Secret-Header-For-Test: 1
Content-Type: text/plain
Content-Length: 4

aa

a
``` 

- 정상 작동시 response
```
11111
```

- 현재 response
```
AA

A
```

위의 결과를 바탕으로`X-Secret-Header-For-Test` 헤더의 첫 번째 문자를 바디의 길이(줄바꿈 `\n` 포함)만큼 반복하여 만드는 걸로 예상됨

**Comment by skamo3** [comment]
해당 내용 아직 완벽하게 이해가 되지 않아서 만나서 더 자세히 들어보도록 할게요

**Comment by skamo3** [comment]
이슈 해결 완료
HTTP request로 들어오는 헤더들은 신경쓰지 않고 metaVariable만 만들어서 넣어주고 있었는데
request로 들어오는 헤더들 앞에 "HTTP_" 를 붙여서 envp로 함께 넣으니 동작
